// Automatic CSAB playhead selection and transition policy.
#include "automatic_playback.h"

#include "../player/player_pose_scan.h"
#include "authored_playback.h"
#include "pose_evaluation_internal.h"
#include "skeleton_draw_bridge.h"

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <unordered_map>
#include <utility>

// Measured single-clip walk-stop alignment data. Generated by
// tools/gen_walk_stop_sweet.py from the childlink_v2 rig.
#include "../tables/zelda3d_walk_stop_sweet.inc"

// Drive an auto-replaced model by its OWN OoT3D CSAB (animName). Two playhead modes:
//   PHASE-LOCK (n64AnimLength>4): the OoT3D CSAB is driven at the SAME fractional progress as the
//     actor's live N64 animation (csab_frame = (n64CurFrame/n64AnimLength) * csab_duration). This
//     is the fix for "OoT3D anims too fast" — the CSAB free-ran at a fixed `rate` regardless of how
//     fast the N64 game logic was actually advancing the anim, so a slow N64 walk looked sped-up.
//     Locking to N64 progress makes the OoT3D motion match the N64 motion's tempo exactly.
//   FREE-RUN (stub idle, n64AnimLength<=4, or duration unknown): self-managed per-model playhead at
//     `rate` frames/draw. N64 idles are often 2-frame fidget stubs with no meaningful progress to
//     lock to (see memory n64-idle-stub-no-phaselock), so we free-run the full OoT3D idle instead.
// animName==NULL -> bind pose. The CSAB wraps the frame internally (Csab::animFrame REPEAT).
//
// MORPH (#8/#86, keystone fix #2): `morphWeight` is the live N64 skelAnime->morphWeight (1.0 on the
// transition frame, ramping linearly to 0). When a transition is detected (the resolved CSAB name
// changes while morphWeight>0) we FREEZE the outgoing clip+frame and, while morphWeight>0, cross-fade
// the new clip toward that frozen pose — exactly the N64 SkelAnime morph model (docs/anim_system.md
// "THE MORPH"). Without this the auto/CSAB path hard-cuts every transition (1-frame arm/limb pops).
// gZelda3dMorph (REPL `morph 0|1`, env ZELDA3D_MORPH default on) gates it for A/B verification.
extern "C" {
int gZelda3dMorph = -1;
// Logic-frame clock (= play->gameplayFrames), set by the Link draw path each frame. The walk-stop
// synthetic morph must advance ONCE per LOGIC frame, not per draw (headless renders many draws/tick).
int gZelda3dLogicFrame = 0;
}

// Last CSAB name + resolved playhead the AUTO path drove each model with, so REPL `boneinfo` can
// dump the live per-bone pose at the exact clip/frame currently on screen (verification tooling —
// debug_journal 2026-07-15-epona-title-animation). Keyed by modelId.
static std::unordered_map<int, std::pair<std::string, float>> sLastAuto;
extern "C" void Zelda3D_RecordLastAuto(int modelId, const char* csab, float frame) {
    if (csab && *csab)
        sLastAuto[modelId] = { std::string(csab), frame };
}

// The CSAB name + RESOLVED playhead the AUTO path last drove `modelId` with. The resolved frame is
// the one the pose was actually sampled at (phase-locked or free-run), which is the only frame a
// per-clip side channel — Link's `.faceb` facial track — may be sampled at, since sampling the raw
// N64 curFrame would desync the face from the pose whenever the CSAB and the N64 clip differ in
// length. Returns 0 if this model has never been driven by the auto path.
extern "C" int Zelda3D_LastAutoAnim(int modelId, const char** outCsab, float* outFrame) {
    auto it = sLastAuto.find(modelId);
    if (it == sLastAuto.end())
        return 0;
    if (outCsab)
        *outCsab = it->second.first.c_str();
    if (outFrame)
        *outFrame = it->second.second;
    return 1;
}

extern "C" void Zelda3D_UpdateAnimAuto(int modelId, const char* animName, float rate, float n64CurFrame,
                                       float n64AnimLength, float morphWeight) {
    static std::unordered_map<int, float> frames;
    static std::unordered_map<int, std::string> lastCsab; // per-model: which CSAB the playhead is on
    static std::unordered_map<int, float> lastFrame;      // last incoming frame rendered (freeze src)
    static std::unordered_map<int, std::string> morphOut; // frozen outgoing CSAB during a morph
    static std::unordered_map<int, float> morphOutFrame;  // frozen outgoing frame
    // OoT3D walk-STOP synthetic morph state (port of FUN_002be4c4 — see §6e + the block below).
    static std::unordered_map<int, float> locoStopW;         // synthetic morph weight (1->0)
    static std::unordered_map<int, float> locoStopRate;      // per-LOGIC-frame decrement = 1/morphFrames
    static std::unordered_map<int, std::string> locoStopEnd; // phase-chosen end CSAB (R/L)
    static std::unordered_map<int, int> locoStopLF;          // last logic frame we advanced on
    static std::unordered_map<int, float> locoStopFrame;     // walk_end playhead (0, advances after morph)
    if (!animName || !*animName) {
        frames.erase(modelId);
        lastCsab.erase(modelId);
        lastFrame.erase(modelId);
        morphOut.erase(modelId);
        morphOutFrame.erase(modelId);
        locoStopW.erase(modelId);
        locoStopRate.erase(modelId);
        locoStopEnd.erase(modelId);
        locoStopLF.erase(modelId);
        locoStopFrame.erase(modelId);
        Zelda3D_UpdateAnim(modelId, nullptr, 0);
        return;
    }
    if (gZelda3dMorph < 0) {
        const char* v = getenv("ZELDA3D_MORPH");
        gZelda3dMorph = (v != NULL && v[0] == '0') ? 0 : 1;
    }
    if (!gZelda3dMorph)
        morphWeight = 0.0f;

    // --- incoming frame f (phase-lock to the N64 anim's progress, else free-run) ---
    Zelda3D_AuthoredPoseInputs poseInputs;
    const float dur = Zelda3D_ResolveAuthoredPoseInputs(modelId, animName, &poseInputs)
                          ? static_cast<float>(poseInputs.animation->duration())
                          : 0.0f;
    bool locked = (n64AnimLength > 4.0f && n64CurFrame >= 0.0f && dur > 0.0f);
    auto lcIt = lastCsab.find(modelId);
    bool csabChanged = (lcIt == lastCsab.end()) || (lcIt->second != animName);

    // --- OoT3D walk-STOP morph (single-CSAB-rig realization; oot3d-decomp player_anim_states.md §6e) -
    // The loco->walk_end transition cross-fades from the frozen leg pose into walk_end@0 with a
    // PHASE-PROPORTIONAL morph length. OoT3D's FUN_002be4c4 chooses endR/endL by the leg phase and both
    // ends are reachable because OoT3D walks with a foot-split walk_L/walk_R clip; Zelda3D has ONE walk
    // clip so only endL is reachable (see the block below for the measured proof + why the direct decomp
    // port regresses). The morph (OoT3D case 3) holds curFrame pinned at 0 during the cross-fade, then
    // walk_end plays out (playSpeed 1.0). nml_walk_free is exactly 29 frames == OoT3D's phase range.
    bool incomingWalkEnd = (strstr(animName, "walk_end") != nullptr);
    if (incomingWalkEnd && csabChanged && lcIt != lastCsab.end() &&
        strstr(lcIt->second.c_str(), "walk_free") != nullptr) {
        float phi = lastFrame.count(modelId) ? lastFrame[modelId] : 0.0f; // outgoing walk_free phase
        phi = std::fmod(phi, (float)kWalkStopPhaseCount);
        if (phi < 0.0f)
            phi += (float)kWalkStopPhaseCount;
        // This IS the faithful single-CSAB-rig realization of the OoT3D morph — NOT a stopgap for it.
        // Directly porting the decomp leg-phase formula (FUN_002be4c4: pick endR when leg-phase<14 with
        // sweet spot 11, else endL with sweet spot 26; morphFrames = rem*fv8*4) was TESTED here
        // 2026-07-23 (this session) and REGRESSES to a 119 deg pop, for a reason K=0 does not cure:
        // FUN_002be4c4 is faithful to OoT3D's FOOT-SPLIT walk (walk_L/walk_R), where BOTH walk_endR@0
        // and walk_endL@0 are reachable from the current stride. Zelda3D renders ONE clip (nml_walk_free),
        // and its walk_endR@0 pose sits ~90 deg from nml_walk_free@ANY phase (the endR settling spine is
        // simply not in the single walk cycle — kWalkStopGapR is 85..94 deg at every phase). So the
        // decomp's phase<14 -> endR pick forces an unreachable pose. SEPARATELY, our rig's endL sweet
        // spot (min kWalkStopGapL) is at phase ~8, NOT the decomp's phase 26 (a real K offset for the
        // END-CLIP alignment — distinct from the WALK-POSE K, which unk_868 phase-lock did drive to 0),
        // so the decomp's endL morph-length would also be mis-sized. Both facts are properties of the
        // single-clip rig; the genuinely faithful fix is to port OoT3D's walk_L/walk_R blend so endR is
        // reachable (§6e OPEN, out of scope for the pop fix). Until then THIS is correct: interpolate the
        // MEASURED walk_free@φ -> end@0 max-bone gap (kWalkStopGapR/L, a rig pose property — measured, not
        // tuned), pick the actually-reachable end (the smaller gap => ~always endL), and size the cross-
        // fade to keep each rendered frame under the oracle's stop ceiling (18.3 deg/frame; ours measures
        // 14.2 worst across 8 phases — tools/walk_stop_phase_sweep.py).
        int i0 = (int)phi % kWalkStopPhaseCount;
        int i1 = (i0 + 1) % kWalkStopPhaseCount;
        float t = phi - (float)i0;
        float gapR = kWalkStopGapR[i0] + (kWalkStopGapR[i1] - kWalkStopGapR[i0]) * t;
        float gapL = kWalkStopGapL[i0] + (kWalkStopGapL[i1] - kWalkStopGapL[i0]) * t;
        bool wantR = (gapR <= gapL);
        float gap = wantR ? gapR : gapL;
        // Budget = the oracle's measured walk-stop ceiling (18.3 deg/frame, §6e STATUS) divided by the
        // measured ~1.3x amplification from this table's LOCAL per-bone gap to the RENDERED world-rotation
        // jump (parent-chain propagation; 23.6 rendered vs 18 local in the phase sweep). Sizing morphFrames
        // off this bounds the RENDERED per-frame jump to oracle parity. Derived, not tuned.
        const float kOracleWalkStopBudget = 14.0f;
        float morphFrames = gap / kOracleWalkStopBudget;
        if (morphFrames < 2.0f)
            morphFrames = 2.0f;
        if (morphFrames > 6.0f)
            morphFrames = 6.0f;
        // Choose endR/endL by the smaller measured gap (override the N64 R/L pick — N64's leg cycle phase
        // is decoupled from Zelda3D's free-run φ). Preserve the incoming name's prefix/suffix (cl_ / _free)
        // by only flipping the R/L letter.
        std::string en = animName;
        size_t rp = en.find("endR"), lp = en.find("endL");
        if (wantR && lp != std::string::npos)
            en[lp + 3] = 'R';
        else if (!wantR && rp != std::string::npos)
            en[rp + 3] = 'L';
        locoStopEnd[modelId] = en;
        locoStopW[modelId] = 1.0f;
        locoStopRate[modelId] = 1.0f / morphFrames;
        locoStopLF[modelId] = gZelda3dLogicFrame;
        locoStopFrame[modelId] = 0.0f;    // OoT3D startFrame = 0
        morphOut[modelId] = lcIt->second; // frozen walk pose source
        morphOutFrame[modelId] = phi;
    }
    if (!incomingWalkEnd) { // left walk_end (e.g. -> idle): drop the synthetic morph
        locoStopW.erase(modelId);
        locoStopRate.erase(modelId);
        locoStopEnd.erase(modelId);
        locoStopLF.erase(modelId);
        locoStopFrame.erase(modelId);
    } else if (locoStopW.count(modelId)) {
        // Render walk_end @ its playhead, cross-faded from the frozen walk pose by the synthetic
        // weight. Per the N64 trace + OoT3D case-3: curFrame is pinned during the morph, then plays
        // forward (playSpeed 1.0) once the morph completes. Advance ONCE per logic frame.
        const std::string& en = locoStopEnd[modelId];
        float w = locoStopW[modelId];
        float ef = locoStopFrame[modelId];
        if (w > 0.0f && morphOut.count(modelId)) {
            Zelda3D_UpdateAnimAuthoredMorph(modelId, en.c_str(), ef, morphOut[modelId].c_str(), morphOutFrame[modelId],
                                            w);
        } else {
            Zelda3D_UpdateAnim(modelId, en.c_str(), ef);
            morphOut.erase(modelId);
            morphOutFrame.erase(modelId);
        }
        if (gZelda3dAnimDebug && modelId == Zelda3D_LinkModelId()) {
            fprintf(stderr, "SOH3D WALKSTOP: end=%s f=%.1f synthW=%.3f rate=%.3f morphOut=%s@%.1f\n", en.c_str(), ef, w,
                    locoStopRate[modelId], morphOut.count(modelId) ? morphOut[modelId].c_str() : "(none)",
                    morphOut.count(modelId) ? morphOutFrame[modelId] : -1.0f);
            fflush(stdout);
        }
        if (gZelda3dLogicFrame != locoStopLF[modelId]) {
            locoStopLF[modelId] = gZelda3dLogicFrame;
            float nw = w - locoStopRate[modelId];
            locoStopW[modelId] = (nw > 0.0f) ? nw : 0.0f;
            if (nw <= 0.0f)
                locoStopFrame[modelId] = ef + 1.0f; // advance after morph done
        }
        // Track the RENDERED end name (we may have flipped R/L vs the N64 anim) + its playhead so the
        // following walk_end->idle transition freezes the pose we actually drew (else the idle morph
        // blends from the wrong endR/L pose = an ~88deg hand pop). "walk_endR_free" does NOT contain
        // "walk_free", so the entry guard above won't re-trigger on subsequent walk_end frames.
        lastCsab[modelId] = en;
        lastFrame[modelId] = ef;
        return;
    }

    float f;
    if (locked) {
        float phase = n64CurFrame / n64AnimLength;
        phase -= std::floor(phase); // wrap into [0,1)
        f = phase * dur;
        frames[modelId] = f; // keep the free-run playhead in sync for a later mode switch
    } else {
        // FREE-RUN. Restart from 0 whenever the CSAB changes, so a one-shot (a wave, a hand-off)
        // plays from its start instead of resuming at the previous anim's frame.
        float& pf = frames[modelId];
        if (csabChanged)
            pf = 0.0f;
        f = pf;
        pf += rate;
    }

    // --- morph bookkeeping: on a real transition, freeze the outgoing clip at its last frame ---
    if (csabChanged) {
        if (morphWeight > 0.0f && lcIt != lastCsab.end()) {
            morphOut[modelId] = lcIt->second; // the clip we're leaving
            auto lfIt = lastFrame.find(modelId);
            morphOutFrame[modelId] = (lfIt != lastFrame.end()) ? lfIt->second : 0.0f;
        } else {
            morphOut.erase(modelId);
            morphOutFrame.erase(modelId); // hard cut / first anim
        }
    }
    if (morphWeight <= 0.0f) {
        morphOut.erase(modelId);
        morphOutFrame.erase(modelId);
    }
    lastCsab[modelId] = animName;
    lastFrame[modelId] = f;
    Zelda3D_RecordLastAuto(modelId, animName, f); // for REPL `boneinfo` live-frame dump

    if (gZelda3dAnimDebug && modelId == Zelda3D_LinkModelId() && (csabChanged || morphWeight > 0.0f)) {
        fprintf(stderr, "SOH3D ANIM XTRANS: %s f=%.2f morphW=%.3f morphOut=%s outFrame=%.2f%s\n", animName, f,
                morphWeight, (morphOut.count(modelId) ? morphOut[modelId].c_str() : "(none)"),
                (morphOut.count(modelId) ? morphOutFrame[modelId] : -1.0f), csabChanged ? " [CHANGE]" : "");
        fflush(stdout);
    }
    auto moIt = morphOut.find(modelId);
    if (moIt != morphOut.end() && morphWeight > 0.0f) {
        Zelda3D_UpdateAnimAuthoredMorph(modelId, animName, f, moIt->second.c_str(), morphOutFrame[modelId],
                                        morphWeight);
    } else {
        Zelda3D_UpdateAnim(modelId, animName, f);
    }
}
