#!/usr/bin/env python3
"""Replacement-coverage report: how close is Zelda3D to 100% OoT3D graphics replacement.

Defines the denominator for "100% coverage" and surfaces the ACTIONABLE gaps. For every N64
object (object_table.h) it asks: is there an OoT3D /actor/zelda_<name>.zar (directly or via a
verified gen_object_zars.ALIAS) and is it mapped? Objects with no OoT3D actor archive are
classified (effect / cutscene / scene-object bundle / texture / keep / item / player) so we
know they need a DIFFERENT path (scene geometry, item models, player) — not the per-actor swap.

Also lists the OoT3D /actor ZARs that NO N64 object points to yet, with each ZAR's main CMB
identity — that list is the candidate pool for new verified ALIASes (the real object->ZAR gap).

Writes COVERAGE.md (committed, the living coverage dashboard). Needs ZELDA3D_OOT3D_ROM.
Run: . ./.env && python3 tools/coverage_report.py
"""
import os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ctr_romfs import CtrRom
from zar import Zar
from gen_object_zars import ALIAS, alias_path

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OBJ_TABLE = os.path.join(REPO, "Shipwright/soh/include/tables/object_table.h")
OUT = os.path.join(REPO, "COVERAGE.md")

# Name-prefix classification for object_* segments that have NO OoT3D /actor ZAR — tells us which
# REPLACEMENT PATH they belong to (so "no actor zar" isn't conflated with "uncovered"). Order
# matters: first matching rule wins.
NOZAR_CLASS = [
    (re.compile(r"_anime\d*$|^demo|opening_demo"), "cutscene", "cutscene rig — special anim path"),
    (re.compile(r"_tex$"),                          "texture",  "texture-only object — no mesh"),
    (re.compile(r"^mjin_|^fire$|^magic|^warp\d"),   "effect",   "effect/particle — likely no OoT3D model"),
    (re.compile(r"^o[ABE]\d|_objects$|^spot|^shop_dungen$"), "scene", "scene-object bundle — scene-geometry path"),
    (re.compile(r"^link_"),                         "player",   "Link/player — dedicated player path"),
    (re.compile(r"keep"),                           "keep",     "shared keep object"),
    (re.compile(r"^gi_|^b_heart$|^medal$|^pu_box$"),"item",     "item/pickup — item-model path"),
]


def classify_nozar(base):
    for rx, cat, desc in NOZAR_CLASS:
        if rx.search(base):
            return cat, desc
    return "unknown", "no OoT3D actor ZAR; replacement path TBD"


def main():
    rom = CtrRom(os.environ["ZELDA3D_OOT3D_ROM"])
    zarset = {f.path for f in rom.iter_files() if f.path.endswith(".zar")}
    actor_zars = sorted(z for z in zarset if z.startswith("/actor/zelda_"))

    objects = []  # (id, base, enum)
    for line in open(OBJ_TABLE):
        m = re.search(r"/\*\s*0x([0-9A-Fa-f]+)\s*\*/\s*DEFINE_OBJECT\(\s*([A-Za-z0-9_]+)\s*,\s*(OBJECT_[A-Z0-9_]+)", line)
        if not m:
            continue
        oid = int(m.group(1), 16)
        seg = m.group(2)
        if not seg.startswith("object_"):
            continue
        objects.append((oid, seg[len("object_"):], m.group(3)))

    matched_zars = set()
    mapped, gaps_by_class = [], {}
    for oid, base, enum in objects:
        direct = "/actor/zelda_%s.zar" % base
        alias = alias_path(ALIAS[base], zarset) if base in ALIAS else None
        if direct in zarset:
            mapped.append((base, direct)); matched_zars.add(direct)
        elif alias:
            mapped.append((base, alias)); matched_zars.add(alias)
        else:
            cat, desc = classify_nozar(base)
            gaps_by_class.setdefault(cat, []).append((base, desc))

    # OoT3D /actor models nothing points to -> candidate ALIAS pool (the real object->ZAR gap).
    unmatched = []
    for z in actor_zars:
        if z in matched_zars:
            continue
        try:
            zz = Zar(rom.read(next(f for f in rom.iter_files() if f.path == z)))
            cmbs = [f.name for f in zz.files if f.name.lower().endswith(".cmb")]
            main = cmbs[0] if cmbs else "(no cmb)"
        except Exception as e:
            main = "ERR %s" % e
        unmatched.append((z.replace("/actor/zelda_", "").replace(".zar", ""), main))

    lines = []
    lines.append("# Zelda3D replacement coverage")
    lines.append("")
    lines.append("GENERATED by `tools/coverage_report.py` — the living dashboard for 100% OoT3D")
    lines.append("graphics replacement. Per-actor object->ZAR coverage + what still needs a path.")
    lines.append("")
    lines.append("## Per-actor object -> ZAR")
    lines.append("- **%d** object_* segments total." % len(objects))
    lines.append("- **%d mapped** to an OoT3D /actor model (direct name or verified alias)." % len(mapped))
    nozar = sum(len(v) for v in gaps_by_class.values())
    lines.append("- **%d have no OoT3D /actor model** (need a different path or have no equivalent):" % nozar)
    for cat in sorted(gaps_by_class):
        items = sorted(gaps_by_class[cat])
        lines.append("  - **%s** (%d): %s" % (cat, len(items), items[0][1]))
        lines.append("    - " + ", ".join(b for b, _ in items))
    lines.append("")
    lines.append("## Candidate object->ZAR gaps: OoT3D /actor models nothing maps to (%d)" % len(unmatched))
    lines.append("Each is a real OoT3D actor model not yet pointed to by any N64 object. Add a")
    lines.append("VERIFIED `ALIAS` in gen_object_zars.py (confirm identity via the CMB name) when an")
    lines.append("N64 object corresponds. Many are items (gi_*) / keep / Link handled by other paths.")
    lines.append("")
    lines.append("| OoT3D zar | main CMB |")
    lines.append("|---|---|")
    for nm, main in unmatched:
        lines.append("| %s | `%s` |" % (nm, main))
    lines.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print("wrote %s: %d objects, %d mapped, %d no-actor-zar, %d unmatched OoT3D actor models"
          % (OUT, len(objects), len(mapped), nozar, len(unmatched)))
    for cat in sorted(gaps_by_class):
        print("  no-zar/%s: %d" % (cat, len(gaps_by_class[cat])))


if __name__ == "__main__":
    main()
