#!/usr/bin/env python3
"""gen_walk_stop_sweet.py — bake the walk-STOP morph table for zelda3d_anim.cpp.

For each integer free-run phase φ of nml_walk_free (duration 29), emit the MAX per-bone local-rotation
gap (deg) between walk_free@φ and each end anim's frame 0 (nml_walk_endR_free@0 / nml_walk_endL_free@0).
The §6e walk-stop cross-fade blends the frozen walk pose → end@0, so this gap IS the angular distance the
morph must cover. Driving morphFrames = gap / OOT3D_BUDGET (the oracle's measured ~18°/frame walk-stop
ceiling) bounds the per-frame velocity to oracle parity, and picking the end with the smaller gap chooses
the nearer continuation — replacing the decomp's leg-phase sweet-spot math, which assumes a CSAB↔leg-phase
offset K=0 that does NOT hold for Zelda3D's single-CSAB (non-blend) walk, so it let morphFrames collapse to
~0 at the wrong φ → the 119° arm snap (measured, tools/walk_stop_phase_sweep.py).

bone9 (upper-pivot/spine twist) is INCLUDED and is decisive for the R/L choice: endR@0 and endL@0
differ ~90° on bone9 because they continue OPPOSITE-foot strides (the torso counter-twist). walk@φ's
spine matches exactly ONE of them, so the min-gap pick selects the stride-correct end; choosing the
other swings the spine 90° and that propagates to every arm bone (the measured 38° shoulder pop).

Output: Shipwright/soh/src/zelda3d/zelda3d_walk_stop_sweet.inc  (two 29-float arrays gapR[]/gapL[]).
"""
from __future__ import annotations
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cmb as C, csab as A
from ctr_romfs import CtrRom
from zar import Zar
from walk_stop_sweet import local_rotations, _geo_angle, ZAR, CMB, WALK, ENDR, ENDL

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "..", "Shipwright", "soh", "src", "zelda3d", "zelda3d_walk_stop_sweet.inc")
BONES = list(range(1, 22))   # all body bones (incl. bone9 spine twist — decisive for R/L, see above)


def main():
    rom = CtrRom(os.environ["ZELDA3D_OOT3D_ROM"])
    z = Zar(rom.read(rom.get(ZAR)))

    def load(n):
        c = [f for f in z.files if f.name == n] or \
            [f for f in z.files if f.name.endswith("/" + n.rsplit("/", 1)[-1])]
        return A.Csab(z.read(c[0]))

    model = C.Cmb(z.read([f for f in z.files if f.name == CMB][0]))
    walk, endR, endL = load(WALK), load(ENDR), load(ENDL)
    dur = walk.duration
    pR0 = local_rotations(model, endR, 0.0, BONES)
    pL0 = local_rotations(model, endL, 0.0, BONES)

    def maxgap(pa, pb):
        return max(_geo_angle(pa[b], pb[b]) for b in BONES if b in pa and b in pb)

    gapR, gapL = [], []
    for i in range(dur):
        pw = local_rotations(model, walk, float(i), BONES)
        gapR.append(maxgap(pw, pR0))
        gapL.append(maxgap(pw, pL0))

    def fmt(arr):
        return ", ".join(f"{v:.1f}f" for v in arr)

    with open(OUT, "w") as f:
        f.write("// GENERATED by tools/gen_walk_stop_sweet.py — DO NOT EDIT BY HAND.\n")
        f.write("// Per nml_walk_free free-run phase φ (0..28), the MAX per-bone local-rotation gap (deg)\n")
        f.write("// from walk_free@φ to each walk-end anim @ frame 0. The §6e walk-stop morph must cover\n")
        f.write("// this gap; morphFrames = gap / oracle-budget bounds per-frame velocity to oracle parity.\n")
        f.write("// Ground truth: oot3d-decomp docs/player_anim_states.md §6e; measured childlink_v2 rig.\n")
        f.write(f"static const int kWalkStopPhaseCount = {dur};\n")
        f.write(f"static const float kWalkStopGapR[{dur}] = {{ {fmt(gapR)} }};\n")
        f.write(f"static const float kWalkStopGapL[{dur}] = {{ {fmt(gapL)} }};\n")
    print(f"wrote {os.path.normpath(OUT)}")
    print(f"  gapR range [{min(gapR):.1f}, {max(gapR):.1f}]  gapL range [{min(gapL):.1f}, {max(gapL):.1f}]")


if __name__ == "__main__":
    main()
