#!/usr/bin/env python3
"""Generate the committed MM-sceneNum -> MM3D-scene-folder-name table.

The MM counterpart of tools/gen_scene_names.py. `play->sceneNum` is the SceneID enum value and
SceneID is generated from 2ship/include/tables/scene_table.h via DEFINE_SCENE in order, so the enum
value equals the table row index. We emit a positional `const char*` array indexed by sceneNum.

MM3D reuses the N64 internal scene segment names verbatim, lower-cased: ALL 102 N64 scenes resolve
to a `/scenes/<name>_<room>_info.zsi` in the MM3D ROM with no overrides needed (measured, not
assumed — the generator verifies every name against the ROM and reports any miss).

NOTE the path differs from OoT3D: MM3D uses `/scenes/` (plural), OoT3D uses `/scene/`.

Names only (no ROM assets) -> safe to commit.
Run: ZELDA3D_MM3D_ROM=<path.3ds> python3 tools/gen_mm_scene_names.py
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCENE_TABLE = os.path.join(REPO, "2ship/include/tables/scene_table.h")
OUT = os.path.join(REPO, "2ship/2s2h/zelda3d/mm3d_scene_names.inc")

# Scenes with no MM3D counterpart map to NULL -> the engine falls back to the N64 room.
OVERRIDES: dict = {}


def _load_env() -> None:
    envp = os.path.join(REPO, ".env")
    if not os.path.isfile(envp):
        return
    for line in open(envp):
        m = re.match(r'\s*(?:export\s+)?([A-Z0-9_]+)\s*=\s*"?([^"\n]*)"?', line)
        if m:
            os.environ.setdefault(m.group(1), m.group(2))


def n64_scenes():
    """[(sceneNum, segment_name_or_None, SCENE_ENUM)] in table order.

    MM's macro is DEFINE_SCENE(_name, _enumValue, ...) -- the enum is the SECOND arg (OoT's is
    third). DEFINE_SCENE_UNSET(_enumValue) marks an empty slot from the original game; it still
    CONSUMES a sceneNum, so it must be emitted as NULL or every later index shifts."""
    out = []
    for line in open(SCENE_TABLE):
        m = re.search(r"DEFINE_SCENE\(\s*([A-Za-z0-9_]+)\s*,\s*(SCENE_[A-Z0-9_]+)", line)
        if m:
            out.append((len(out), m.group(1), m.group(2)))
            continue
        m = re.search(r"DEFINE_SCENE_UNSET\(\s*(SCENE_[A-Z0-9_]+)", line)
        if m:
            out.append((len(out), None, m.group(1)))
    return out


def mm3d_scene_names(rom):
    names = set()
    for f in rom.iter_files():
        m = re.match(r"/scenes/(.+?)_\d+_info\.zsi$", f.path)
        if m:
            names.add(m.group(1))
            continue
        m = re.match(r"/scenes/(.+?)_info\.zsi$", f.path)
        if m:
            names.add(m.group(1))
    return names


def main() -> int:
    _load_env()
    rom_path = os.environ.get("ZELDA3D_MM3D_ROM")
    if not rom_path or not os.path.isfile(rom_path):
        sys.exit("set ZELDA3D_MM3D_ROM (see .env)")
    from ctr_romfs import CtrRom

    have = mm3d_scene_names(CtrRom(rom_path))
    scenes = n64_scenes()

    rows, mapped, missing = [], 0, []
    for num, seg, enum in scenes:
        if seg is None:  # DEFINE_SCENE_UNSET -- empty slot, keeps indices aligned
            rows.append((num, enum, "(unset)", "NULL"))
            continue
        name = OVERRIDES.get(enum, seg.lower().replace("_scene", ""))
        if name in have:
            rows.append((num, enum, seg, '"%s"' % name))
            mapped += 1
        else:
            rows.append((num, enum, seg, "NULL"))
            missing.append((enum, seg, name))

    w = max((len(e) for _n, e, _s, _v in rows), default=8)
    lines = [
        "// GENERATED by tools/gen_mm_scene_names.py -- do not edit by hand.",
        "// MM sceneNum (SceneID enum, == scene_table.h row index) -> MM3D scene folder name,",
        "// used to build /scenes/<name>_<R>_info.zsi. NULL = no MM3D scene (fall back to the N64",
        "// room). Names only; no ROM-derived assets.",
        "// NOTE: MM3D uses /scenes/ (plural); OoT3D uses /scene/.",
        "// %d/%d scenes mapped." % (mapped, len(scenes)),
        "static const char* const kMm3dSceneNames[] = {",
    ]
    for num, enum, seg, val in rows:
        lines.append("    /* 0x%02X %-*s (%s) */ %s," % (num, w, enum, seg, val))
    lines.append("};")
    open(OUT, "w").write("\n".join(lines) + "\n")

    print("wrote %s: %d/%d scenes mapped" % (os.path.relpath(OUT, REPO), mapped, len(scenes)))
    if missing:
        print("no MM3D scene for:")
        for enum, seg, guess in missing:
            print("   %-34s segment=%-24s tried=%s" % (enum, seg, guess))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
