#!/usr/bin/env python3
"""Generate the redistributable OoT3D interpolated-trig table metadata."""

from __future__ import annotations

import argparse
import os
import re
import subprocess
from pathlib import Path


REPO = Path(__file__).resolve().parent.parent
DECOMP = REPO / "oot3d-decomp"
OUTPUT = REPO / "Shipwright/soh/src/zelda3d/behaviors/actor/boss_fd/oot3d_trig_table.inc"
TABLE_ADDRESS = 0x004DF42C
ENTRY_COUNT = 256
ENTRY_STRIDE = 16
COMPONENT_OFFSETS = (0, 4, 8, 12)
WORD_RE = re.compile(r"^\s*(0x[0-9a-fA-F]+)\s*=\s*(0x[0-9a-fA-F]+)", re.MULTILINE)


def addresses() -> list[int]:
    return [
        TABLE_ADDRESS + index * ENTRY_STRIDE + offset
        for index in range(ENTRY_COUNT)
        for offset in COMPONENT_OFFSETS
    ]


def read_words() -> dict[int, int]:
    env = os.environ.copy()
    env["OOT3D_READ_VAS"] = ",".join(f"0x{address:08x}" for address in addresses())
    result = subprocess.run(
        [
            "analyzeHeadless",
            "build/ghidra",
            "oot3d",
            "-process",
            "code.bin",
            "-noanalysis",
            "-scriptPath",
            "tools/ghidra_scripts",
            "-postScript",
            "ReadWord.py",
        ],
        cwd=DECOMP,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=True,
    )
    words = {int(address, 16): int(word, 16) for address, word in WORD_RE.findall(result.stdout)}
    missing = [address for address in addresses() if address not in words]
    if missing:
        raise RuntimeError(f"Ghidra did not return table word 0x{missing[0]:08x}")
    return words


def render(words: dict[int, int]) -> str:
    lines = [
        "// Generated by tools/gen_oot3d_trig_table.py from OoT3D code.bin VA 0x004DF42C.",
        "// Each row is { sin, cos, sin-delta, cos-delta } as exact IEEE-754 bits.",
        "constexpr std::array<std::array<std::uint32_t, 4>, 256> kTrigTableBits = {{",
    ]
    for index in range(ENTRY_COUNT):
        base = TABLE_ADDRESS + index * ENTRY_STRIDE
        values = ", ".join(f"0x{words[base + offset]:08X}U" for offset in COMPONENT_OFFSETS)
        lines.append(f"    {{ {values} }},")
    lines.extend(("}};", ""))
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the committed table is stale")
    args = parser.parse_args()
    generated = render(read_words())
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text() != generated:
            raise SystemExit(f"stale generated table: {OUTPUT.relative_to(REPO)}")
        print(f"verified {OUTPUT.relative_to(REPO)}")
        return 0
    OUTPUT.write_text(generated)
    print(f"wrote {OUTPUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
