#!/usr/bin/env python3
"""Generate the GAME's N64-anim -> OoT3D-CSAB table: zelda3d_animmap.inc.

Source of truth: tools/animmap_source.py (animmap.json overlaid with the shared
charcompare_overrides.tsv). This file USED to be hand-maintained; it is now GENERATED so it
stays in lockstep with the charcompare tool's index (same source, same overrides). Hand-verified
corrections go in tools/skeldata/charcompare_overrides.tsv, NOT here.

Emits ZELDA3D_ANIMMAP("<n64 anim OTR path>", "<CSAB base>") entries consumed by zelda3d.c.
Run:  python3 tools/gen_animmap_inc.py
"""
import os

import animmap_source

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "Shipwright/soh/src/zelda3d/zelda3d_animmap.inc")


def main():
    src, n_ov = animmap_source.load()

    lines = []
    lines.append("// GENERATED by tools/gen_animmap_inc.py — do not edit by hand.")
    lines.append("// N64-animation -> OoT3D-CSAB map for AUTO skinned actors. Key = the actor's live")
    lines.append("// N64 animation OTR path (skelAnime->animation, minus the __OTR__ prefix); value =")
    lines.append("// the CSAB base name played on the replacement OoT3D model. An unlisted anim falls")
    lines.append("// back to the model's default idle (Zelda3D_AutoModelDefaultAnim).")
    lines.append("//")
    lines.append("// Source of truth = tools/skeldata/animmap.json (auto-matched) overlaid with")
    lines.append("// tools/skeldata/charcompare_overrides.tsv (hand-verified). The charcompare tool's")
    lines.append("// index is generated from the SAME source, so the two never diverge. To change a")
    lines.append("// mapping, edit the overrides TSV and rerun gen_animmap_inc.py + gen_charcompare_index.py.")
    lines.append("typedef struct {")
    lines.append("    const char* n64otr; // N64 animation OTR resource path (no __OTR__ prefix)")
    lines.append("    const char* csab;   // OoT3D CSAB base name to play")
    lines.append("    const char* zar;    // model ZAR this entry is specific to, or NULL for any model.")
    lines.append("                        // Set only for OTR paths shared across skeletons (object_os_anime")
    lines.append("                        // bank: km1/Kokiri vs ane/Cucco-Lady) so the resolver can pick the")
    lines.append("                        // right CSAB by the live model's ZAR (Zelda3D_AutoModelZar).")
    lines.append("} Zelda3DAnimMap;")
    lines.append("")
    lines.append("#define ZELDA3D_ANIMMAP(otr_, csab_) { otr_, csab_, NULL }")
    lines.append("#define ZELDA3D_ANIMMAP_Z(otr_, csab_, zar_) { otr_, csab_, zar_ }")
    lines.append("")
    # An OTR path that appears under more than one ZAR is a SHARED-bank anim (e.g. object_os_anime
    # used by both the km1 Kokiri skeleton and the ane Cucco-Lady skeleton). Those entries are emitted
    # ZAR-qualified so the runtime resolver disambiguates them per model; everything else is generic.
    otr_zars = {}
    for d in src:
        for r in d["rows"]:
            otr_zars.setdefault(r["otr"], set()).add(d["zar"])
    shared = {otr for otr, zs in otr_zars.items() if len(zs) > 1}
    lines.append("static const Zelda3DAnimMap kZelda3dAnimMaps[] = {")
    n_rows = 0
    for d in src:
        lines.append("    // ---- %s (%s) ----" % (d["zar"], d["object"]))
        for r in d["rows"]:
            mark = "  // OVERRIDE (was %s)" % (r["auto"] or "<none>") if r["overridden"] else ""
            if r["otr"] in shared:
                lines.append('    ZELDA3D_ANIMMAP_Z("%s", "%s", "%s"),%s'
                             % (r["otr"], r["csab"], d["zar"], mark))
            else:
                lines.append('    ZELDA3D_ANIMMAP("%s", "%s"),%s' % (r["otr"], r["csab"], mark))
            n_rows += 1
    lines.append("};")
    lines.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print("wrote %s: %d entries across %d objects (%d overrides applied)"
          % (OUT, n_rows, len(src), n_ov))


if __name__ == "__main__":
    main()
