#!/usr/bin/env python3
"""Generate the OoT3D camera-settings VALUES table for the camera-data port.

GROUND TRUTH (derived 2026-07-22, Kokiri-fov divergence session):
- OoT3D keeps the N64 camera data format BYTE-COMPATIBLE:
    sCameraSettings[setting] = { u32 validModes, CameraMode* modes }
    CameraMode               = { s16 funcIdx, s16 valueCnt, CameraModeValue* }
    CameraModeValue          = { s16 val, s16 dataType }   (same CAM_DATA_* enum)
  Verified against the LIVE oracle: harness watchpoint on Camera+0x18 (fov param)
  caught writer PC 0x0023a00c inside FUN_00239fd8 (Normal1), whose decomp reads
    values = [[DAT_0023a348] + setting*8 + 4] + mode*8 + 4
  and the live folded params at Kokiri (setting 1, mode 0) match this table's
  row exactly (fov 52.0 at Camera+0x18 == pair (52, CAM_DATA_FOV)).
- Grezzo RETUNED values in place (e.g. NORMAL0 normal fov 60 -> 52, NORMAL1
  fov 60 -> 55); the table shape and dataType tags are unchanged, so the port
  is a pure data overwrite where the (funcIdx, valueCnt, dataType-sequence)
  structure matches SoH's N64 table. Distance divergences seen at runtime
  (Kakariko dMin/dMax ~46%) are NOT in this table (raw 200/400 == N64) — they
  come from the height-scale formula, a separate camera-code port item.
- sCameraSettings VA = pointer at pool constant VA 0x0023a348 (code.bin is
  mapped at VA 0x100000). The 3DS table has more settings than N64's 0x42
  (Grezzo extras); we emit min(N64 CAM_SET_MAX=0x42, what parses cleanly).

Run: python3 tools/gen_oot3d_camera_values.py   (reads oot3d-decomp/build/code.bin)
"""
import os, struct

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CODE = os.path.join(REPO, "oot3d-decomp", "build", "code.bin")
OUT = os.path.join(REPO, "Shipwright/soh/src/zelda3d/tables/zelda3d_camera_values.inc")
BASE_VA = 0x100000
POOL_TABLE_PTR = 0x0023A348
CAM_SET_MAX = 0x42
CAM_MODE_MAX = 0x15
MAX_VALUES = 40  # sanity cap; real counts are <= ~26


def main():
    d = open(CODE, "rb").read()

    def rd32(va):
        return struct.unpack_from("<I", d, va - BASE_VA)[0]

    def rd16s(va):
        return struct.unpack_from("<h", d, va - BASE_VA)[0]

    def va_ok(va):
        return BASE_VA <= va and (va - BASE_VA) + 4 <= len(d)

    tbl = rd32(POOL_TABLE_PTR)
    settings = []  # per setting: (validModes, [ (funcIdx, [ (val,type) ] ) ] or None)
    for s in range(CAM_SET_MAX):
        valid = rd32(tbl + s * 8)
        modes_va = rd32(tbl + s * 8 + 4)
        if modes_va == 0 or not va_ok(modes_va):
            settings.append((valid, None))
            continue
        modes = []
        for m in range(CAM_MODE_MAX):
            # Mode arrays are COMPACT: length = highest valid mode + 1 (e.g. Horse mask
            # 0x8500018F -> 9 entries). Only read modes whose validModes bit is set —
            # beyond the compact array is unrelated data.
            if not (valid >> m) & 1:
                modes.append((0, []))
                continue
            hdr = rd32(modes_va + m * 8)
            vals_va = rd32(modes_va + m * 8 + 4)
            func = hdr & 0xFFFF
            cnt = hdr >> 16
            if cnt == 0 or cnt > MAX_VALUES or not va_ok(vals_va) or not va_ok(vals_va + cnt * 4 - 4):
                modes.append((func, []))
                continue
            pairs = [(rd16s(vals_va + i * 4), rd16s(vals_va + i * 4 + 2)) for i in range(cnt)]
            modes.append((func, pairs))
        settings.append((valid, modes))

    with open(OUT, "w") as o:
        o.write("// GENERATED by tools/gen_oot3d_camera_values.py — do not edit by hand.\n")
        o.write("// OoT3D sCameraSettings VALUES (code.bin table @ [0x0023a348]), byte-compatible\n")
        o.write("// with the N64 format. Applied over SoH's sCameraSettings at Camera boot where the\n")
        o.write("// (funcIdx, valueCnt, dataType-sequence) structure matches — see the generator\n")
        o.write("// docstring for the derivation and Zelda3D_ApplyOoT3DCameraValues (z_camera.c).\n\n")
        o.write("typedef struct { short val; short dataType; } Zelda3dCamValue;\n")
        o.write("typedef struct { short funcIdx; short valueCnt; const Zelda3dCamValue* values; } Zelda3dCamMode;\n")
        o.write("typedef struct { const Zelda3dCamMode* modes; } Zelda3dCamSetting;\n\n")
        for s, (valid, modes) in enumerate(settings):
            if modes is None:
                continue
            for m, (func, pairs) in enumerate(modes):
                if not pairs:
                    continue
                o.write("static const Zelda3dCamValue kZ3dCamVals_%02x_%02x[] = { " % (s, m))
                o.write(", ".join("{%d,%d}" % p for p in pairs))
                o.write(" };\n")
            o.write("static const Zelda3dCamMode kZ3dCamModes_%02x[] = {\n" % s)
            for m, (func, pairs) in enumerate(modes):
                if pairs:
                    o.write("    { %d, %d, kZ3dCamVals_%02x_%02x },\n" % (func, len(pairs), s, m))
                else:
                    o.write("    { %d, 0, 0 },\n" % func)
            o.write("};\n")
        o.write("\nstatic const Zelda3dCamSetting kZelda3dCameraSettings[] = {\n")
        for s, (valid, modes) in enumerate(settings):
            if modes is None:
                o.write("    { 0 },\n")
            else:
                o.write("    { kZ3dCamModes_%02x },\n" % s)
        o.write("};\n")
    print("wrote %s: %d settings" % (OUT, len(settings)))


if __name__ == "__main__":
    main()
