"""C table rendering for MM animation maps and evidenced defaults."""

from __future__ import annotations

from collections.abc import Mapping, Sequence

from mm_animmap_defaults import resolve_default_anim
from mm_animmap_types import ActorResult


def emit_default_inc(results: Sequence[ActorResult]) -> tuple[str, list[str]]:
    lines = [
        "// Generated by tools/gen_mm_animmap.py -- DO NOT EDIT BY HAND.",
        "// MM3D actor GAR basename -> the CSAB clip to play when the live N64 animation has no",
        "// entry in kMMAnimMaps. The generator selects only an evidenced default. An actor",
        "// absent from this table has no determinable idle and keeps the runtime fallback.",
    ]
    unknown = []
    for result in sorted(results, key=lambda item: item.obj):
        if not result.gar or not result.clips:
            continue
        clip, why = resolve_default_anim(result)
        if clip is None:
            unknown.append(f"{result.obj} ({result.gar}, {len(result.clips)} clips)")
            continue
        lines.append(
            '    {{ "{}", "{}" }},{}// {}'.format(
                result.gar,
                clip,
                " " * max(1, 46 - len(result.gar) - len(clip)),
                why,
            )
        )
    return "\n".join(lines) + "\n", unknown


def emit_inc(results: Sequence[ActorResult], meta: Mapping[str, object]) -> str:
    lines = [
        "// Generated by tools/gen_mm_animmap.py -- DO NOT EDIT BY HAND.",
        "// N64 animation OTR key (no __OTR__ prefix) -> MM3D CSAB clip name.",
        "// Source: 2ship/assets/objects/*/ + the MM3D ROM's /actors/zelda*_*.gar[.lzs]",
        "// Accepted at confidence >= {:.2f}; ambiguous/weak matches are intentionally omitted so".format(
            meta["min_confidence"]
        ),
        "// the actor falls back to its default idle CSAB rather than playing a wrong animation.",
    ]
    entries = 0
    for result in results:
        matched = [match for match in result.matches if match.clip]
        if not matched:
            continue
        width = max(len(match.symbol) for match in matched) + 3
        lines.append(
            f"// ---- {result.obj} ({result.gar}: {len(matched)}/{len(result.matches)} anims, "
            f"{len(result.clips)} clips) ----"
        )
        for match in matched:
            key = f'"{match.symbol}",'
            lines.append(f'    {{ {key:<{width}} "{match.clip}" }},')
            entries += 1
    actor_count = sum(
        1 for result in results if any(match.clip for match in result.matches)
    )
    lines.insert(5, f"// {entries} entries across {actor_count} actors.")
    return "\n".join(lines) + "\n"
