#!/usr/bin/env bash
# Rasterize a crisp HUD button-background disc (the round beveled circle behind the B / C / A
# action buttons) to a grayscale-on-transparent PNG and embed it as a C header the HUD loads at
# runtime (stbi_load_from_memory -> persistent RGBA32). Backlog #31 (UI textures); mirror of
# tools/zelda3d_gen_hud_tex.sh / zelda3d_gen_digit_tex.sh (the reusable SVG->texture pipeline).
#   tools/zelda3d_gen_button_tex.sh
# Requires ImageMagick (magick/convert) with the librsvg delegate.
#
# Combine semantics the N64 HUD button relies on (SETUPDL_39 = G_CC_MODULATEIA_PRIM:
# out.rgb = TEXEL0.rgb * PRIM.rgb, out.a = TEXEL0.a * PRIM.a). PRIM is the per-button colour
# (B=green, C=yellow, A=green...). So a GRAYSCALE disc (rgb=intensity bevel shading, a=circle
# coverage) tints IDENTICALLY to the original 32x32 IA8 gButtonBackgroundTex — the bevel/3D look
# comes from the intensity, the colour from PRIM. We render a flat medium-grey disc with a
# diagonal light(top-left)->dark(bottom-right) bevel RIM, matching the N64 art, at 4x (128x128).
# Output is RGBA32 grayscale fed raw to gDPLoadTextureBlock(G_IM_FMT_RGBA,32b) as in #32.
set -euo pipefail
REPO="$(cd "$(dirname "$0")/.." && pwd)"
OUTDIR="$REPO/scratch/svg"; mkdir -p "$OUTDIR"
HDR="$REPO/Shipwright/soh/src/zelda3d/assets/button_tex_png.h"
# 64x64 (2x the N64 32x32): RGBA32 = 16KB, within the proven HUD-texture load envelope (the #31
# hearts / #32 glyphs are 64x64). The disc is reused as a resident tile by several bare C-button
# texrects whose dsdx is scaled by DIM/32 in z_parameter.c (Zelda3D_ButtonBgTexScale).
DIM=64

RASTER=(magick); command -v magick >/dev/null 2>&1 || RASTER=(convert)

SVG="$OUTDIR/button_bg.svg" PNG="$OUTDIR/button_bg.png"
# viewBox in 0..32 texel space (matches the N64 32x32 tile so texcoord maths stays simple).
# Disc centred at (16,16). Outer rim r=15.3 carries the bevel gradient; the interior r=13.2 is the
# flat medium grey the N64 art shows. The diagonal gradient reproduces the beveled 3D rim
# (bright top-left highlight -> dark bottom-right shadow). Intensities chosen to match the decoded
# N64 texture (interior I~10/15 -> ~#aa, top rim I~14, bottom rim I~3).
cat > "$SVG" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED HUD button-background disc. Grayscale=intensity (the per-button colour is applied
     by the HUD combine via PRIM), alpha=circle coverage. See tools/zelda3d_gen_button_tex.sh. -->
<svg xmlns="http://www.w3.org/2000/svg" width="$DIM" height="$DIM" viewBox="0 0 32 32">
  <defs>
    <linearGradient id="bevel" x1="0.08" y1="0.08" x2="0.92" y2="0.92">
      <stop offset="0.00" stop-color="#fbfbfb"/>
      <stop offset="0.34" stop-color="#bcbcbc"/>
      <stop offset="0.60" stop-color="#727272"/>
      <stop offset="1.00" stop-color="#202020"/>
    </linearGradient>
    <radialGradient id="face" cx="0.40" cy="0.38" r="0.74">
      <stop offset="0.00" stop-color="#bcbcbc"/>
      <stop offset="0.74" stop-color="#a2a2a2"/>
      <stop offset="1.00" stop-color="#828282"/>
    </radialGradient>
  </defs>
  <circle cx="16" cy="16" r="15.4" fill="url(#bevel)"/>
  <circle cx="16" cy="16" r="12.7" fill="url(#face)"/>
</svg>
EOF
"${RASTER[@]}" -background none "$SVG" -resize ${DIM}x${DIM}\! "$PNG"

{
  echo "// GENERATED by tools/zelda3d_gen_button_tex.sh — do not edit."
  echo "// Raw PNG bytes of the crisp HUD button-background disc (grayscale+alpha); decoded at"
  echo "// runtime via stbi_load_from_memory into persistent RGBA32. Backlog #31 (UI textures)."
  echo "#pragma once"
  printf 'static const unsigned char kButtonBgPng[] = {\n'
  od -An -v -tu1 "$PNG" | tr -s ' ' | sed 's/^ //; s/ /,/g; s/$/,/'
  printf '};\n'
  printf 'static const unsigned int kButtonBgPngLen = sizeof(kButtonBgPng);\n'
} > "$HDR"

echo "rasterized button disc -> $PNG ($(wc -c < "$PNG") bytes); wrote $HDR (DIM=$DIM)"
