#!/usr/bin/env bash
# Rasterize the Xbox face-button glyph SVGs (A/B/X/Y) to PNGs and embed them as a single
# C header the HUD loads at runtime (stbi_load_from_memory -> persistent RGBA32). Run after
# editing any assets/zelda3d/xbox_<letter>.svg.
#   tools/zelda3d_gen_xbox_glyphs.sh
# Requires ImageMagick (magick/convert) with the librsvg delegate. Mirror of
# tools/zelda3d_gen_stairs_tex.sh (the reusable SVG->texture pipeline, backlog #32).
set -euo pipefail
REPO="$(cd "$(dirname "$0")/.." && pwd)"
ASSETS="$REPO/Shipwright/soh/assets/zelda3d"
OUTDIR="$REPO/scratch/svg"; mkdir -p "$OUTDIR"
HDR="$REPO/Shipwright/soh/src/zelda3d/assets/xbox_glyphs_png.h"

RASTER=(magick); command -v magick >/dev/null 2>&1 || RASTER=(convert)

{
  echo "// GENERATED by tools/zelda3d_gen_xbox_glyphs.sh from assets/zelda3d/xbox_{a,b,x,y}.svg — do not edit."
  echo "// Raw PNG bytes of the Xbox face-button glyphs; decoded at runtime via stbi_load_from_memory."
  echo "#pragma once"
} > "$HDR"

for L in a b x y; do
  SVG="$ASSETS/xbox_$L.svg"
  PNG="$OUTDIR/xbox_$L.png"
  "${RASTER[@]}" -background none "$SVG" -resize 64x64\! "$PNG"
  U=$(echo "$L" | tr 'a-z' 'A-Z')
  {
    printf 'static const unsigned char kXboxGlyph%sPng[] = {\n' "$U"
    od -An -v -tu1 "$PNG" | tr -s ' ' | sed 's/^ //; s/ /,/g; s/$/,/'
    printf '};\n'
    printf 'static const unsigned int kXboxGlyph%sPngLen = sizeof(kXboxGlyph%sPng);\n' "$U" "$U"
  } >> "$HDR"
  echo "rasterized $SVG -> $PNG ($(wc -c < "$PNG") bytes)"
done

echo "wrote $HDR"
