#!/usr/bin/env bash
# Rasterize a crisp numeric HUD font (0-9 + colon) to grayscale-on-transparent PNGs and embed them
# as a single C header the HUD loads at runtime (stbi_load_from_memory -> persistent RGBA32). These
# replace the blocky N64 8x16 I8 counter digits (gCounterDigit0..9 / gCounterColon) used by the
# rupee / key / ammo / timer / minigame-score counters via Gfx_TextureI8. Backlog #31 (UI textures).
#   tools/zelda3d_gen_digit_tex.sh
# Requires ImageMagick (magick/convert). Mirror of tools/zelda3d_gen_hud_tex.sh.
#
# The counter combine (z_parameter.c) is colour=PRIMITIVE, alpha=TEXEL0*PRIM — i.e. the glyph
# INTENSITY/alpha is the cut-out mask and PRIM is the flat digit colour. So a grayscale glyph
# (rgb=255, a=coverage) reproduces the original exactly, just at higher resolution. On-screen cell
# is 8x16 (1:2), so author at 32x64 to keep aspect.
set -euo pipefail
REPO="$(cd "$(dirname "$0")/.." && pwd)"
OUTDIR="$REPO/scratch/svg"; mkdir -p "$OUTDIR"
HDR="$REPO/Shipwright/soh/src/zelda3d/assets/digit_tex_png.h"
W=32; H=64
FONT="${ZELDA3D_DIGIT_FONT:-Liberation-Sans-Bold}"

RASTER=(magick); command -v magick >/dev/null 2>&1 || RASTER=(convert)

{
  echo "// GENERATED by tools/zelda3d_gen_digit_tex.sh — do not edit."
  echo "// Raw PNG bytes of the crisp HUD counter font (grayscale+alpha); decoded at runtime via"
  echo "// stbi_load_from_memory into persistent RGBA32. Backlog #31 (UI textures)."
  echo "#pragma once"
} > "$HDR"

emit() { # cname glyph
  local CNAME="$1" GLYPH="$2"
  local PNG="$OUTDIR/digit_$CNAME.png"
  # white glyph, centred, on transparent; slight font size < cell so it doesn't touch edges.
  "${RASTER[@]}" -size ${W}x${H} xc:none -font "$FONT" -pointsize 56 -fill white \
    -gravity center -annotate +0+0 "$GLYPH" "$PNG"
  {
    printf 'static const unsigned char kDigit%sPng[] = {\n' "$CNAME"
    od -An -v -tu1 "$PNG" | tr -s ' ' | sed 's/^ //; s/ /,/g; s/$/,/'
    printf '};\n'
    printf 'static const unsigned int kDigit%sPngLen = sizeof(kDigit%sPng);\n' "$CNAME" "$CNAME"
  } >> "$HDR"
  echo "rasterized '$GLYPH' -> $PNG ($(wc -c < "$PNG") bytes)"
}

for d in 0 1 2 3 4 5 6 7 8 9; do emit "$d" "$d"; done
emit Colon ":"

echo "wrote $HDR (cell ${W}x${H}, font $FONT)"
