#!/usr/bin/env bash
# Generate the two assets the HUD's keyboard key badge is composited from:
#
#   1. the BLANK keycap (assets/zelda3d/key_cap.svg -> 64x64 RGBA)
#   2. a fixed-cell glyph ATLAS for the label alphabet, one cell per character
#
# The badge label is NOT baked at build time — it is composited at RUNTIME from whatever key is
# actually bound to the N64 button (zelda3d/hud/zelda3d_hud_tex.cpp Zelda3D_KeyCapTex, fed by
# input/zelda3d_keymap.cpp), so rebinding in the input editor changes the HUD immediately. That is
# why this emits an alphabet rather than one PNG per slot.
#
# The atlas font is the REPO-VENDORED Inconsolata (Shipwright/soh/assets/custom/fonts) rather than a
# system font, so the output is byte-reproducible on any machine — and because it is MONOSPACE, one
# cell width covers every character and the runtime needs no per-glyph advance table.
#
#   tools/zelda3d_gen_key_glyphs.sh
#
# Requires ImageMagick (magick/convert) with the librsvg delegate.
set -euo pipefail
REPO="$(cd "$(dirname "$0")/.." && pwd)"
ASSETS="$REPO/Shipwright/soh/assets/zelda3d"
FONT="$REPO/Shipwright/soh/assets/custom/fonts/Inconsolata-Regular.ttf"
OUTDIR="$REPO/scratch/svg"; mkdir -p "$OUTDIR"
HDR="$REPO/Shipwright/soh/src/zelda3d/assets/key_glyphs_png.h"

RASTER=(magick); command -v magick >/dev/null 2>&1 || RASTER=(convert)

# Label alphabet. Uppercase letters + digits + the punctuation that appears on a US keycap. Keep this
# in sync with the sanitizer in input/zelda3d_keymap.cpp, which folds any SDL key name to this set
# and substitutes '?' for anything outside it. Characters are fed to ImageMagick through a file
# (`label:@file`) rather than the command line so backslash and backtick need no shell/IM escaping.
CHARS='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-=[]\;'"'"',./`?'
CELL_W=20
CELL_H=40
POINTSIZE=34

emit_png_array() { # <png> <cname>
  printf 'static const unsigned char %s[] = {\n' "$2"
  od -An -v -tu1 "$1" | tr -s ' ' | sed 's/^ //; s/ /,/g; s/$/,/'
  printf '};\n'
  printf 'static const unsigned int %sLen = sizeof(%s);\n' "$2" "$2"
}

# --- 1. blank keycap ---------------------------------------------------------------------------
CAP_PNG="$OUTDIR/key_cap.png"
"${RASTER[@]}" -background none "$ASSETS/key_cap.svg" -resize 64x64\! "PNG32:$CAP_PNG"

# --- 2. glyph atlas ----------------------------------------------------------------------------
rm -f "$OUTDIR"/keyglyph_cell_*.png
i=0
while [ "$i" -lt "${#CHARS}" ]; do
  c="${CHARS:$i:1}"
  printf '%s' "$c" > "$OUTDIR/keyglyph_char.txt"
  "${RASTER[@]}" -background none -fill '#222222' -font "$FONT" -pointsize "$POINTSIZE" \
                 -size "${CELL_W}x${CELL_H}" -gravity center "label:@$OUTDIR/keyglyph_char.txt" \
                 "PNG32:$OUTDIR/keyglyph_cell_$(printf '%03d' "$i").png"
  i=$((i + 1))
done
ATLAS_PNG="$OUTDIR/key_alphabet.png"
"${RASTER[@]}" "$OUTDIR"/keyglyph_cell_*.png +append "PNG32:$ATLAS_PNG"

# --- 3. header ---------------------------------------------------------------------------------
{
  echo "// GENERATED by tools/zelda3d_gen_key_glyphs.sh — do not edit."
  echo "// Blank keycap (assets/zelda3d/key_cap.svg) + a monospaced glyph atlas for HUD key badges."
  echo "// The badge LABEL is composited at runtime from the live binding; see Zelda3D_KeyCapTex."
  echo "#pragma once"
  emit_png_array "$CAP_PNG" kKeyCapPng
  emit_png_array "$ATLAS_PNG" kKeyGlyphAtlasPng
  echo "// Atlas layout: one row of ${#CHARS} cells, cell N holds kKeyGlyphChars[N]."
  # Escape for a C string literal — the alphabet contains a backslash and a double quote would too
  # if it were ever added.
  printf 'static const char kKeyGlyphChars[] = "%s";\n' "$(printf '%s' "$CHARS" | sed 's/\\/\\\\/g; s/"/\\"/g')"
  printf 'static const int kKeyGlyphCellW = %d;\n' "$CELL_W"
  printf 'static const int kKeyGlyphCellH = %d;\n' "$CELL_H"
} > "$HDR"

echo "keycap  -> $CAP_PNG ($(wc -c < "$CAP_PNG") bytes)"
echo "alphabet-> $ATLAS_PNG ($(wc -c < "$ATLAS_PNG") bytes, ${#CHARS} cells)"
echo "wrote $HDR"
