#!/usr/bin/env bash
# Rasterize crisp HUD heart textures (full / 3-4 / half / quarter / empty) to grayscale-on-
# transparent PNGs and embed them as a single C header the HUD loads at runtime
# (stbi_load_from_memory -> persistent RGBA32). Run after editing the heart shape below.
#   tools/zelda3d_gen_hud_tex.sh
# Requires ImageMagick (magick/convert) with the librsvg delegate. Mirror of
# tools/zelda3d_gen_xbox_glyphs.sh / zelda3d_gen_stairs_tex.sh (the reusable SVG->texture pipeline,
# backlog #31 "UI textures").
#
# IA semantics the N64 HUD heart relies on (z_lifemeter.c HealthMeter_Draw combine
# (PRIM-ENV)*TEXEL0+ENV, alpha TEXEL0*PRIM): a heart texture is a SOLID heart silhouette
# (alpha=coverage everywhere) whose INTENSITY encodes the fill — bright (->PRIM, the red) in the
# filled bottom fraction, dark (->ENV) in the empty top fraction. So we render a dark heart base
# then a bright clipped rect over the bottom fraction; the GPU combine tints it red. The output is
# RGBA32 grayscale (rgb=intensity, a=silhouette) fed raw to gDPLoadTextureBlock as in #32.
set -euo pipefail
REPO="$(cd "$(dirname "$0")/.." && pwd)"
OUTDIR="$REPO/scratch/svg"; mkdir -p "$OUTDIR"
HDR="$REPO/Shipwright/soh/src/zelda3d/assets/heart_tex_png.h"
DIM=64

RASTER=(magick); command -v magick >/dev/null 2>&1 || RASTER=(convert)

# Heart silhouette path in a 0..64 viewBox: apex (bottom point) at y=58, top lobes at y=6,
# width spanning x=4..60. The vertical fill span is therefore [6,58] = 52 units.
HEART='M32 58 C 14 44 4 34 4 22 C 4 12 12 6 20 6 C 26 6 30 9 32 13 C 34 9 38 6 44 6 C 52 6 60 12 60 22 C 60 34 50 44 32 58 Z'
TOP=6; BOT=58; SPAN=52

{
  echo "// GENERATED by tools/zelda3d_gen_hud_tex.sh — do not edit."
  echo "// Raw PNG bytes of the crisp HUD heart textures (grayscale+alpha); decoded at runtime"
  echo "// via stbi_load_from_memory into persistent RGBA32. Backlog #31 (UI textures)."
  echo "#pragma once"
} > "$HDR"

emit() { # name fraction
  local NAME="$1" FRAC="$2"
  local SVG="$OUTDIR/heart_$NAME.svg" PNG="$OUTDIR/heart_$NAME.png"
  # bright fill covers from the apex up by FRAC of the vertical span; fillTop = BOT - SPAN*FRAC
  local FILLTOP
  FILLTOP=$(awk -v b=$BOT -v s=$SPAN -v f="$FRAC" 'BEGIN{printf "%.2f", b - s*f}')
  cat > "$SVG" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED HUD heart ($NAME, fill=$FRAC). Grayscale=intensity (red tint applied by the HUD
     combine), alpha=heart silhouette. See tools/zelda3d_gen_hud_tex.sh. -->
<svg xmlns="http://www.w3.org/2000/svg" width="$DIM" height="$DIM" viewBox="0 0 64 64">
  <defs><clipPath id="h"><path d="$HEART"/></clipPath></defs>
  <g clip-path="url(#h)">
    <rect x="0" y="0" width="64" height="64" fill="#202020"/>
    <rect x="0" y="$FILLTOP" width="64" height="64" fill="#ffffff"/>
  </g>
  <path d="$HEART" fill="none" stroke="#000000" stroke-width="3.4" stroke-opacity="0.72" stroke-linejoin="round"/>
</svg>
EOF
  "${RASTER[@]}" -background none "$SVG" -resize ${DIM}x${DIM}\! "$PNG"
  {
    printf 'static const unsigned char kHeart%sPng[] = {\n' "$NAME"
    od -An -v -tu1 "$PNG" | tr -s ' ' | sed 's/^ //; s/ /,/g; s/$/,/'
    printf '};\n'
    printf 'static const unsigned int kHeart%sPngLen = sizeof(kHeart%sPng);\n' "$NAME" "$NAME"
  } >> "$HDR"
  echo "rasterized $NAME (fill=$FRAC, top=$FILLTOP) -> $PNG ($(wc -c < "$PNG") bytes)"
}

emit Full        1.0
emit ThreeQuarter 0.75
emit Half         0.5
emit Quarter      0.25
emit Empty        0.0

echo "wrote $HDR (DIM=$DIM)"
