#!/usr/bin/env bash
# Rasterize the custom stair SVG to a PNG and embed it as a C header that the renderer
# loads at runtime (stbi_load_from_memory). Run this after editing stairs_stone.svg.
#   tools/zelda3d_gen_stairs_tex.sh
# Requires ImageMagick (magick/convert) with the librsvg delegate.
set -euo pipefail
REPO="$(cd "$(dirname "$0")/.." && pwd)"
SVG="$REPO/Shipwright/soh/assets/zelda3d/stairs_stone.svg"
OUTDIR="$REPO/scratch/svg"; mkdir -p "$OUTDIR"
PNG="$OUTDIR/stairs_stone.png"
HDR="$REPO/Shipwright/soh/src/zelda3d/assets/stairs_stone_png.h"

RASTER=(magick); command -v magick >/dev/null 2>&1 || RASTER=(convert)
"${RASTER[@]}" -background none "$SVG" -resize 256x256\! "$PNG"

{
  echo "// GENERATED by tools/zelda3d_gen_stairs_tex.sh from assets/zelda3d/stairs_stone.svg — do not edit."
  echo "// Raw PNG bytes of the custom stair texture; decoded at runtime via stbi_load_from_memory."
  echo "#pragma once"
  printf 'static const unsigned char kStairStonePng[] = {\n'
  od -An -v -tu1 "$PNG" | tr -s ' ' | sed 's/^ //; s/ /,/g; s/$/,/'
  printf '};\n'
  printf 'static const unsigned int kStairStonePngLen = sizeof(kStairStonePng);\n'
} > "$HDR"

echo "wrote $PNG ($(wc -c < "$PNG") bytes) -> $HDR"
